language: go

go:
  - 1.12.x
  - 1.13.x

services:
  - postgresql

before_script:
  - psql -c 'create database admin_test;' -U postgres

env:
  - GO111MODULE=on

script:
  - go vet
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic