language: go
cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

go:
  - 1.12.x
  - 1.13.x

services:
  - postgresql

before_script:
  - psql -c 'create database admin_test;' -U postgres

env:
  global:
    - GO111MODULE=on
    - GOARCH=amd64

script:
  - go vet
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

notifications:
email:
  on_success: change
  on_failure: always