language: go

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

matrix:
  fast_finish: true
  include:
  - go: 1.12.x
    env: GO111MODULE=on
  - go: 1.13.x
  - go: master

services:
  - postgresql

before_script:
  - psql -c 'create database admin_test;' -U postgres

script:
  - make vet
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
email:
  on_success: change
  on_failure: always
