version: '3.4'
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '8082:8082'
    depends_on:
      - db
    restart: on-failure
    environment:
      DATABASE_URL: postgres://postgres@db:5432/admin_dev?sslmode=disable
    networks:
      - web

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: admin_dev
      POSTGRES_USER: postgres
    ports:
      - '5433:5432'
    volumes:
      - postgres:/var/lib/postgresql/data:z
    networks:
      - web
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - 'CMD-SHELL'
        - 'pg_isready --dbname=admin_dev --host=localhost --username=postgres'

networks:
  web:

volumes:
  postgres:
    driver: local
